services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        restart: unless-stopped
        volumes:
            - .:/var/www/html
        env_file:
            - .env
        depends_on:
            - mysql
        networks:
            - laravel_network

    # Nginx Web Server
    nginx:
        image: nginx:alpine

        restart: unless-stopped
        ports:
            - "${NGINX_PORT:-8001}:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    # MySQL Database
    mysql:
        image: mysql:8.0

        restart: unless-stopped
        ports:
            - "${MYSQL_PORT:-3307}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel_db}
            MYSQL_USER: ${DB_USERNAME:-laravel_user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-laravel_password}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

    # Adminer (Database Management Tool)
    adminer:
        image: adminer

        restart: unless-stopped
        ports:
            - "${ADMINER_PORT:-8081}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        depends_on:
            - mysql
        networks:
            - laravel_network


networks:
    laravel_network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
